---
title: "Üye Olun"
---

Üye olmak için Başvuru Formunu doldurarak derneğimiz e-posta adresine (info@cahspar.org.tr) gönderiniz.

[Başvuru Formunu indiriniz](assets/uye-basvuru-formu.pdf)

Madde 3 - Dernekler Kanunu’nda belirtilen şartları taşıyan, derneğin amaç ve ilkelerini benimsemiş ve bu doğrultuda çalışmayı kabul etmiş herkes derneğe üye olmak için başvurabilir.

Derneğin üyelik türleri şunlardır:

- Asil üyelik
- Fahri üyelik
- Onursal üyelik

Asil üyelik: Fiil ehliyetine sahip, derneğin amaç ve ilkelerini benimseyen, mevzuatın öngördüğü koşulları taşıyan akademisyenler, araştırmacılar, uzmanlar, işverenler, gerçek ve tüzel kişiler bu derneğe üye olma hakkına sahiptir.

Fahri üyelik: Dernek Yönetim Kurulu kararı ile derneğe yakın ilgi gösterenler, önemli çalışmaları olanlar veya derneğin amacıyla ilgili alanlarda katkı sağlamış kişiler fahri üye olabilir.

Onursal üyelik: Derneğe maddi ve manevi bakımdan önemli katkı sağlamış kişiler, yönetim kurulu kararıyla onursal üye kabul edilebilir.

Madde 4 - Dernek başkanlığına yapılan üyelik başvurusu, dernek yönetim kurulunca en geç otuz gün içinde kabul veya reddedilir. Sonuç yazılı olarak başvuru sahibine bildirilir.

Derneğin asli üyeleri, kurucular ile müracaatları üzerine yönetim kurulu kararıyla üyeliğe kabul edilen kişilerdir.

Madde 5 - Dernek üyeleri eşit haklara sahiptir. Her üyenin genel kurulda bir oy hakkı vardır. Fahri üyelerin oy hakkı yoktur.

Dernek üyeleri, genel kurul tarafından belirlenen giriş ve aylık/yıllık aidatı öderler.
